### ISSUE TITLE
EXT volume mounting: check if a EXT volume holds a journal before attempting to recover/start it.

### ISSUE THREAD

**Issue by mid-kid** [DarkMatterCore/libusbhsfs#14]
**Is your feature request related to a problem? Please describe.**
For performance reasons, I've formatted some of my drives with `mkfs.ext4 -O '^has_journal'`. I don't store a lot of important things on these drives (they're merely used as temporary extra storage) so doing this made sense to me. However, when trying the example program in this repo, mounting the drive stops at https://github.com/DarkMatterCore/libusbhsfs/blob/main/source/lwext4/ext.c#L68

**Describe the solution you'd like**
Don't replay or start a new journal if the `has_journal` filesystem flag isn't set.

**Describe alternatives you've considered**
`tune2fs -O has_journal` allows me to create a journal without formatting the drive, which is what I'm doing for now, but eventually it'd be nice to just have it work without a journal.

**Comment by DarkMatterCore** [comment]
@mid-kid Thanks for reporting this issue.

This actually seems to be a problem within lwext4 itself. Both `__ext4_recover()` and `__ext4_journal_start()` check if the `has_journal` flag is set in the EXT superblock - however, `__ext4_journal_start()` returns `EOK` [if the flag isn't set](https://github.com/gkostka/lwext4/blob/733b2c40d7121900e339bee8784977467a9fe8c9/src/ext4.c#L489), while `__ext4_recover()` returns `ENOTSUP` [under the same condition](https://github.com/gkostka/lwext4/blob/733b2c40d7121900e339bee8784977467a9fe8c9/src/ext4.c#L557). lwext4 doesn't enforce the usage of journal-related functions by itself, nor is the `has_journal` flag verified anywhere else in its code, which explains why both public functions check this flag.

A quick solution would be checking for the availability of this flag ourselves, in a similar manner to the way the EXT version is [currently determined](https://github.com/DarkMatterCore/libusbhsfs/blob/e600835981430a73087f005728055be184d69cfd/source/lwext4/ext.c#L121). I'll implement this change to the `dev` branch in a few minutes.

Opening an issue in the [lwext4 repository](https://github.com/gkostka/lwext4) about this problem would be the best course of action in the long run, though. Even if the default return value from `__ext4_recover()` isn't changed, being more specific about it in the [comments](https://github.com/gkostka/lwext4/blob/733b2c40d7121900e339bee8784977467a9fe8c9/include/ext4.h#L183) from the `ext4.h` header file would greatly help avoid confusions like this.

By the way, you may or may not already know this, but the replay journal feature can be disabled altogether on all supported filesystem types by the application using the library at runtime via `usbHsFsSetFileSystemMountFlags()`. Just don't set `UsbHsFsMountFlags_ReplayJournal` as part of the bitmask passed to that function.

**Comment by DarkMatterCore** [comment]
@mid-kid The fix has been pushed to the `dev` branch. Feel free to test it whenever you want.

**Comment by mid-kid** [comment]
I was under the impression that `UsbHsFsMountFlags_ReplayJournal` would still create a new journal if it wasn't present. Thanks for clarifying.
I'm not sure what should be reported to the lwext4 guys? Checking for `ENOTSUP` and just silently moving on in that case would seem sensible enough, and avoid having to check the filesystem flag for yourself. Are you saying it should be better documented like that?

**Comment by DarkMatterCore** [comment]
> I was under the impression that `UsbHsFsMountFlags_ReplayJournal` would still create a new journal if it wasn't present. Thanks for clarifying.
> I'm not sure what should be reported to the lwext4 guys? Checking for `ENOTSUP` and just silently moving on in that case would seem sensible enough, and avoid having to check the filesystem flag for yourself. Are you saying it should be better documented like that?
No problem, mate. Glad to help. If you have any other suggestions, feel free to create additional issues to address them.

And yes, it should be better documented. The confusion arose from [these comments](https://github.com/gkostka/lwext4/blob/733b2c40d7121900e339bee8784977467a9fe8c9/include/ext4.h#L154-L166) in the `ext4.h` header file. As you can see, it states journaling functions are transparent even with EXT volumes that have no journal at all.

It also states both `ext4_journal_start()` and `ext4_recover()` must be called after `ext4_mount()`, but the exact order isn't mentioned - I had to take a look at the examples for that, which don't perform any type of error checking.
