### ISSUE TITLE
Id like support for TexFAT  

### ISSUE THREAD

**Issue by fennectech** [DarkMatterCore/libusbhsfs#17]
**Is your feature request related to a problem? Most platforms support EXFAT  however exfat is not exactly robust.  However an varient called texfat which provides a redundant FAT

**Describe the solution you'd like**
Support for TEXFAT

**Describe alternatives you've considered**
None exist

**Additional context**
NTFS is my current filesystem  but its not as universal as exfat  texfat is backwords compatable with exfat however this can result in the fats getting out of sync.   So a routine to validate that the fat is in tact and to update the redundant fat would be nice

https://docs.microsoft.com/en-us/previous-versions/cc907927(v=msdn.10)?redirectedfrom=MSDN

**Comment by DarkMatterCore** [comment]
We're currently using FatFs to handle support for FAT filesystems.

FatFs itself doesn't support TexFAT - it'd be preferrable to pitch a feature request like this directly to ChaN. If FatFs gets updated, I'll gladly update libusbhsfs as well.
