### ISSUE TITLE
NTFS-3G: inode deletion fails for compressed NTFS volumes.

### ISSUE THREAD

**Issue by DarkMatterCore** [DarkMatterCore/libusbhsfs#20]
[libusbhsfs.log](https://github.com/DarkMatterCore/libusbhsfs/files/8102927/libusbhsfs.log)

Logfile provided by @fennectech. They're using a compressed 4TB NTFS volume -- the error itself seems to originate from NTFS-3G:

```
[2022-02-19 12:49:40.812947616] ntfs_delete -> Could not delete inode cache entry for /test_dir/libusbhsfs-example.txt
 (file "dir.c", line 2051, level 0x80).
[2022-02-19 12:49:40.925302924] ntfs_delete -> Could not delete inode cache entry for /test_dir/test.txt
 (file "dir.c", line 2051, level 0x80).
[2022-02-19 12:49:40.958309248] ntfs_delete -> Could not delete inode cache entry for /test_dir
 (file "dir.c", line 2051, level 0x80).
```

Gotta take a look and fix the error ASAP.

**Comment by fennectech** [comment]
:).  If you need SSH access to a machine with this filesystem mounted let me know.   Else if you want a copy of htis filesystem send me a 4TB hdd and i will DD it for you    We can work out the details in discord

**Comment by DarkMatterCore** [comment]
@fennectech Could you please test the latest release? I believe the creation of LRU caches should have taken care of the issue.

**Comment by fennectech** [comment]
Alright. Will do.  Soon as the file transfer im in the middle of is finished

**Comment by fennectech** [comment]
can you shoot me the files?

**Comment by DarkMatterCore** [comment]
> can you shoot me the files?

Just grab the NRO from the GPL build archive in the releases tab.

**Comment by fennectech** [comment]
Ok

**Comment by fennectech** [comment]
Looks like we can close this   Cheers
