### ISSUE TITLE
Build fails on windows if these are not installed:

### ISSUE THREAD

**Issue by mrdude2478** [DarkMatterCore/libusbhsfs#21]
For anyone compiling on clean installed devkitpro mysy2 install on windows, if the following packages are not installed the build hangs when trying to create the tar.bz2 file to install.

pacman -S tar
pacman -S diffutils
pacman -S pkg-config

Also I installed bzip2 (pacman -S bzip2), not sure if this was needed or not.

**Comment by DarkMatterCore** [comment]
Definitely an overlook. I'll fix it right away on the `dev` branch.

**Comment by DarkMatterCore** [comment]
Fixed in ff9d30ece6b30e5bda44838d3350801e07b5525f. Thanks.

**Comment by mrdude2478** [comment]
Thanks for fixing.
