### ISSUE TITLE
GPL version build error

### ISSUE THREAD

**Issue by urherenow** [DarkMatterCore/libusbhsfs#25]
ISC build fine

GPL (which is built while building nxdumptool, I guess?) halts on an implicit declaration of function: NVolFreeSpaceKnown in ntfs_dev.c

If I add -Wno-implicit-function-declaration to the cflags, it then hangs on an incompatible pointer type in ntfs_disk_io.c. (int vs long unsigned int).

Trying to make install on ISC build throws a ton of errors, even though actually building it works without error.

**Comment by DarkMatterCore** [comment]
Most certainly a duplicate of https://github.com/DarkMatterCore/libusbhsfs/issues/23.

Run `make fs-libs` before building the library -- this is especially needed if lwext4 and/or ntfs-3g updates were introduced in the codebase, and older versions of either of those libraries are currently installed in DKP's portlibs.

**Comment by urherenow** [comment]
Tried to read through the other issue, and it's a complete mess, what had to be done to get things to build. not even sure from what makefile pacman is being called, but I saw you mention taking care of people with dkp-pacman. The fact is that the script should try dkp-pacman FIRST, then fall back to pacman if dkp-pacman doesn't exist. That's the whole point of dkp-pacman in the first place. It's used if a distro already has pacman.

**Comment by Whovian9369** [comment]
> That's the whole point of dkp-pacman in the first place. It's used if a distro already has pacman.
Except... it isn't? `dkp-pacman` is supposed to be used only on systems already without `pacman`.

Even [the official wiki page for devkitpro pacman installation](https://devkitpro.org/wiki/devkitPro_pacman#Customising_Existing_Pacman_Install) uses "normal" `pacman` commands in the section for using their repos with systems, quote,
> which come with pacman already installed i.e. Arch or Msys2. **Do Not** follow these instructions if you have dkp-pacman or used the devkitPro installer

So `dkp-pacman` is meant for systems without an existing `pacman` installation.

**Comment by urherenow** [comment]
Oh. I stand corrected. But I already used the installer years ago, so I’m not supposed to do the steps on that page.

Can we agree that it makes sense in both cases to try dkp-pacman first, and pacman as a fallback, for the same reason though?

**Comment by DarkMatterCore** [comment]
No, because devkitPro can be installed as a repository for systems with

**Comment by DarkMatterCore** [comment]
Issue #23 was just rooted in the fact that `make fs-libs` wasn't ran before attempting to build libusbhsfs itself. Even though libntfs-3g had already been installed beforehand, they were actually using an older version of the library, thus it needed to be manually updated. Furthermore, they were also using more than one DKP installation at a time and forgot to update their environment variables accordingly.

The lwext4 and libntfs-3g portlibs we provide will require manual installation for the foreseeable future. Certain stances from the DKP staff on how filesystem and storage device interaction should be handed prevents the inclusion of these portlibs into their pacman repository.

**Comment by DarkMatterCore** [comment]
In any case, you may want to check the `dev` branch -- it has been sitting on some unmerged commits for some months now, and some of them do introduce changes to all Makefiles and package building scripts.

I'll eventually make a new release.

**Comment by urherenow** [comment]
Great, I’ll have a look. Thank you!

**Comment by DarkMatterCore** [comment]
No problem, glad to help.

We may change the way these unofficial portlibs are handled in the future. Right now, libusbhsfs' Makefile expects the updated portlibs to be readily available beforehand, and thus so does nxdumptool itself (which always builds libusbhsfs instead of installing it).

Always building the portlibs can make the process an awful lot longer, especially on underpowered hardware.

For the time being, I'll just update the readme on the `dev` branch.
