### ISSUE TITLE
I get the following error when trying to build

### ISSUE THREAD

**Issue by sskyNS** [DarkMatterCore/libusbhsfs#30]
**Describe the bug**

**To Reproduce**

**Please fill the following information:**
![QQ截图20240301123916](https://github.com/DarkMatterCore/libusbhsfs/assets/121209531/0e10177d-cfe5-4ca1-a886-8a68b69d7ada)

- Horizon OS (Switch FW) version: [e.g. 10.0.0]
- CFW: [e.g. Atmosphère, SX OS, etc.]
- CFW version: [e.g. 0.11.1, 2.9.4, etc.]
- Atmosphère launch method (if applicable): [e.g. Hekate, fusee-primary]
- libusbhsfs version: [e.g. 0.0.2]
- Homebrew launch method: [e.g. title override, applet]
- USB Mass Storage device specs: [e.g. WD My Passport 1 TB, exFAT partition]

**Logfile**
Make sure you're using an application that's linked against the debug version of the library, and upload your logfile located at `sdmc:/libusbhsfs.log`.

**Additional context**
![QQ截图20240301123916](https://github.com/DarkMatterCore/libusbhsfs/assets/121209531/93285a61-4c9d-4d75-a13a-13aa906d33ea)

**Comment by DarkMatterCore** [comment]
Please read the `How to install` section from the readme. You need to install both `switch-ntfs-3g` and `switch-lwext` packages beforehand.

You may need to run a system upgrade beforehand with `pacman -Syu` if you can't install the filesystem libraries.
