### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Owen-sys** [DarkMatterCore/libusbhsfs#8]
Can you use this to make the switch notice an sd card via dock?

**Comment by DarkMatterCore** [comment]
Depends on what you want to achieve.

If you mean using a SD card + USB MMC reader to simulate the Switch's SD card slot, then nope.

If you mean using the same combination as an available UMS device for homebrew apps to use, then yes. Card readers with multiple slots are supported as well.

**Comment by Owen-sys** [comment]
well i kinda understand but i might be wrong so im talking about using the sd card via usb adapter connected to the docks usb to use homebrew

**Comment by DarkMatterCore** [comment]
@Owen-sys Yes, that's supported.

**Comment by Owen-sys** [comment]
omg really? I need to set this up as soon as i get my thing back

**Comment by DarkMatterCore** [comment]
Wait, no, that's exactly what I meant you *can't* do in my first comment.

```
If you mean using a SD card + USB MMC reader to simulate the Switch's SD card slot, then nope.
```

You can't use this to e.g. load CFW + emuMMC + apps from a connected UMS device.

**Comment by Owen-sys** [comment]
oh?

**Comment by DarkMatterCore** [comment]
This only serves as a library to provide existent homebrew apps the ability to mount and use USB Mass Storage devices to read/write data.

**Comment by Owen-sys** [comment]
so theres no possible/current way to do this right now?

**Comment by DarkMatterCore** [comment]
Not without heavily modifying Atmosphère, I'm afraid. And that would require reimplementing the whole fs sysmodule.

**Comment by Owen-sys** [comment]
oh

**Comment by DarkMatterCore** [comment]
Yeah. Sorry to be the bearer of bad news. Hope you can get you micro SD card slot fixed sometime soon.

**Comment by Owen-sys** [comment]
thanks
